### 查询课程信息
POST {{content_host}}/content/course/list?page=1&pageSize=4
Content-Type: application/json

{
  "auditStatus": "",
  "courseName": "java",
  "publishStatus": ""
}

### 查询系统字典表
GET {{system_host}}/system/dictionary/all

### 查询课程分类
GET {{content_host}}/content/course-category/tree-nodes

### 新增课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": "10",
  "qq": "232442",
  "wechat": "24242545",
  "phone": "18571139145",
  "validDays": 365,
  "mt": "1-3",
  "st": "1-3-2",
  "name": "Java实战",
  "pic": "",
  "teachmode": "200002",
  "users": "many many many people",
  "tags": "spring",
  "grade": "204002",
  "objectives": "",
  "uiCategoryTreeSelected": [
    "1-3",
    "1-3-2"
  ],
  "description": "java spring boot\nspring cloud",
  "originalPrice": "100"
}
